### ISSUE TITLE
Mark as dormant?

### ISSUE THREAD

**Issue by noamross** [ropensci/zenodo#20]
I wonder if we should mark this development status as "suspended" and maybe move it over to ropenscilabs as there hasn't been active work in three years and there isn't a full test suite, and I think the Zenodo API may have changed in that time.

**Comment by karthik** [comment]
Thanks for checking in. At the all hands meeting we had this past week we decided that I'd drop the ball on various things so I have time to work on this. Is it a problem for this repo to be here? There are various other dormant projects on this org

**Comment by noamross** [comment]
No need to mark it dormant if you're going to be on it again.  But "in development",  according to repostatus.org, means that the package has reached stable status but is still actively developed.  Should this be WIP instead? [![Project Status: WIP – Initial development is in progress, but there has not yet been a stable, usable release suitable for the public.](http://www.repostatus.org/badges/latest/wip.svg)](http://www.repostatus.org/#wip)

Bigger discussion on the repos that I'll open elsewhere.

**Comment by karthik** [comment]
I guess I'll just delete the repo for now.

**Comment by noamross** [comment]
Don't do that!  I think you'll lose the issues.
